"""Add password_hash column to agents table

Revision ID: 23db207390bd
Revises: 3f3e0eed289d
Create Date: 2024-08-29 17:07:22.535820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23db207390bd'
down_revision = '3f3e0eed289d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
